// <auto-generated />
using System;
using Abasto.Negocio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Abasto.Negocio.Infrastructure.Migrations
{
    [DbContext(typeof(NegocioContext))]
    [Migration("20211107030208_Iniciando")]
    partial class Iniciando
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.ingComentario", b =>
                {
                    b.Property<long>("comId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("comActivo")
                        .HasColumnType("bit");

                    b.Property<string>("comDescripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("comFecha")
                        .HasColumnType("datetime");

                    b.Property<long>("pubId")
                        .HasColumnType("bigint");

                    b.Property<long>("usrId")
                        .HasColumnType("bigint");

                    b.HasKey("comId");

                    b.HasIndex("pubId");

                    b.HasIndex("usrId");

                    b.ToTable("ingComentario");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.ingPublicacion", b =>
                {
                    b.Property<long>("pubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("pubDescripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("pubFecha")
                        .HasColumnType("datetime");

                    b.Property<string>("pubImagen")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("usrId")
                        .HasColumnType("bigint");

                    b.HasKey("pubId");

                    b.HasIndex("usrId");

                    b.ToTable("ingPublicacion");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.ingUsuario", b =>
                {
                    b.Property<long>("usrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("usrActivo")
                        .HasColumnType("bit");

                    b.Property<string>("usrEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("usrFechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("usrNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("usrTelefono")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("usrId");

                    b.ToTable("ingUsuario");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.ingComentario", b =>
                {
                    b.HasOne("Abasto.Negocio.Core.Entities.ingPublicacion", "ingPublicacion")
                        .WithMany("ingComentario")
                        .HasForeignKey("pubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abasto.Negocio.Core.Entities.ingUsuario", "ingUsuario")
                        .WithMany("ingComentario")
                        .HasForeignKey("usrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ingPublicacion");

                    b.Navigation("ingUsuario");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.ingPublicacion", b =>
                {
                    b.HasOne("Abasto.Negocio.Core.Entities.ingUsuario", "ingUsuario")
                        .WithMany("ingPublicacion")
                        .HasForeignKey("usrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ingUsuario");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.ingPublicacion", b =>
                {
                    b.Navigation("ingComentario");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.ingUsuario", b =>
                {
                    b.Navigation("ingComentario");

                    b.Navigation("ingPublicacion");
                });
#pragma warning restore 612, 618
        }
    }
}
