// <auto-generated />
using System;
using Abasto.Negocio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Abasto.Negocio.Infrastructure.Migrations
{
    [DbContext(typeof(NegocioContext))]
    partial class NegocioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.IngComentario", b =>
                {
                    b.Property<long>("ComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ComActivo")
                        .HasColumnType("bit");

                    b.Property<string>("ComDescripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ComFecha")
                        .HasColumnType("datetime");

                    b.Property<long>("PubId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuId")
                        .HasColumnType("bigint");

                    b.HasKey("ComId");

                    b.HasIndex("PubId");

                    b.HasIndex("UsuId");

                    b.ToTable("IngComentario");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.IngPublicacion", b =>
                {
                    b.Property<long>("PubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PubDescripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("PubFecha")
                        .HasColumnType("datetime");

                    b.Property<string>("PubImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuId")
                        .HasColumnType("bigint");

                    b.HasKey("PubId");

                    b.HasIndex("UsuId");

                    b.ToTable("IngPublicacion");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.IngUsuario", b =>
                {
                    b.Property<long>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("UsuActivo")
                        .HasColumnType("bit");

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UsuFechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("UsuNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuTelefono")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("UsuId");

                    b.ToTable("IngUsuario");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.IngComentario", b =>
                {
                    b.HasOne("Abasto.Negocio.Core.Entities.IngPublicacion", "Pub")
                        .WithMany("IngComentario")
                        .HasForeignKey("PubId")
                        .IsRequired();

                    b.HasOne("Abasto.Negocio.Core.Entities.IngUsuario", "Usu")
                        .WithMany("IngComentario")
                        .HasForeignKey("UsuId")
                        .IsRequired();

                    b.Navigation("Pub");

                    b.Navigation("Usu");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.IngPublicacion", b =>
                {
                    b.HasOne("Abasto.Negocio.Core.Entities.IngUsuario", "Usu")
                        .WithMany("IngPublicacion")
                        .HasForeignKey("UsuId")
                        .IsRequired();

                    b.Navigation("Usu");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.IngPublicacion", b =>
                {
                    b.Navigation("IngComentario");
                });

            modelBuilder.Entity("Abasto.Negocio.Core.Entities.IngUsuario", b =>
                {
                    b.Navigation("IngComentario");

                    b.Navigation("IngPublicacion");
                });
#pragma warning restore 612, 618
        }
    }
}
